# Generated by Django 2.2.2 on 2020-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
