# Generated by Django 2.2.2 on 2020-04-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_music', '0003_imagegallery_pic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grahics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic_name', models.CharField(default='My Pic', max_length=50)),
                ('graphic_pic', models.ImageField(upload_to='img_gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('signature', models.ImageField(upload_to='sign/')),
            ],
        ),
    ]
