# Generated by Django 2.2.2 on 2020-04-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_music', '0004_grahics_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grahics',
            name='graphic_pic',
            field=models.ImageField(upload_to='graphics-work/'),
        ),
    ]
