# Generated by Django 2.2.2 on 2020-04-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_music', '0005_auto_20200403_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grahics',
            new_name='Graphics',
        ),
    ]
