# Generated by Django 2.2.2 on 2020-04-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_music', '0006_auto_20200403_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signature',
            new_name='Signatures',
        ),
    ]
