# Generated by Django 2.2.2 on 2020-04-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_music', '0007_auto_20200403_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signatures',
            new_name='Signature',
        ),
    ]
